#!/bin/bash
echo "Running Setup from $(pwd) with arguments $*"

source "/data/SetupHelper/CommonResources"
BASE_DIR=/data/mastervenus

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	# display initial message
	echo
	echo "mastervenus"
	
	standardActionPrompt
fi

function cleanup ()
{
	echo cleanup
}

#### install code goes here
if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "Installing mastervenus"
	
#    updateFileSets

	installService mastervenus
	cleanup
fi


#### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
	logMessage "Uninstalling mastervenus"
	removeService mastervenus
fi

endScript

