#!/bin/bash
exec 2>&1

#sleep 30
#exit
# ifconfig can1 down
ip link set can1 up type can bitrate 250000
# ifconfig can1 up
ifconfig can1

# basedir=$(dirname $PWD/$0)/..
# cd $basedir
pwd > /tmp/dirname

PYTHONPATH=/data/mastervenus/python-can-develop/:/data/mastervenus/typing_extensions-4.2.0/src python3 mastervenus.py
