#!/bin/bash
exec 2>&1

#sleep 30
#exit
ifconfig can1 down
ip link set can1 up type can bitrate 250000
ifconfig can1 up
ifconfig can1

if [[ $# -eq 0 ]]; then
    basedir=/data/mastervenus/
else #This is the dev version, running from the local directory
    basedir=$(dirname $0)/..
fi

cd $basedir
env PYTHONPATH=python-can-develop/:typing_extensions-4.2.0/src python3 $basedir/mastervenus.py
