#!/bin/bash
logfile=/tmp/mastervenus.tmp
set > $logfile

exec 2>&1

#sleep 30
#exit
ifconfig can1 down
ip link set can1 up type can bitrate 250000
ifconfig can1 up
ifconfig can1

basedir=/data/mastervenus/
cd $basedir
pwd

env PYTHONPATH=python-can-develop/:typing_extensions-4.2.0/src python3 mastervenus.py
